google-gemini/generative-ai-dart

.github/workflows/flutter_sample.yml
.github/workflows/samples.yml
README.md
samples/flutter_app/README.md
samples/flutter_app/pubspec.yaml

- run the samples checks on changes to package:google_generative_ai
- misc readme and CI changes

misc readme and CI changes

---

pkgs/google_generative_ai/analysis_options.yaml
pkgs/google_generative_ai/lib/google_generative_ai.dart
pkgs/google_generative_ai/lib/src/api.dart
pkgs/google_generative_ai/lib/src/error.dart
pkgs/google_generative_ai/lib/src/model.dart

- enable additional lints
- address associated analysis issues

enable additional lints

---

pkgs/google_generative_ai/lib/src/api.dart

Tweak wording of some comments, use enhanced enum features. Try to be consistent about making variables final.

Tweak api.dart

---

README.md
samples/dart/README.md
samples/flutter_app/README.md
samples/flutter_app/analysis_options.yaml

-adjust the readmes to better call out the dart and flutter samples (the main readme we written when we just had dart samples)

adjust the readmes to better call out the dart and flutter samples

---

samples/flutter_app/lib/main.dart

Added a few tweaks like:
- dark theme
- extra white space to give content some room to breathe
- rounded corners on message widget and text field. 
Mobile:
Web:

Update sample app color scheme and component styling

---

samples/flutter_app/.gitignore
samples/flutter_app/README.md
samples/flutter_app/lib/main.dart

This changes from `--dart-define-from-file` to `--dart-define` to simplify the instructions.

Change instructions to use `--dart-define` 

---

samples/flutter_app/lib/main.dart

Make the ListView automatically scroll to the bottom when a new message populates.
https://github.com/google/generative-ai-dart/assets/12416400/c5ede479-2277-45de-92f9-3cb90de2a8a0

automatically scroll down on new message

---

pkgs/google_generative_ai/lib/src/api.dart
pkgs/google_generative_ai/lib/src/client.dart
pkgs/google_generative_ai/lib/src/content.dart

- populate additional dartdoc documentation
Taken from the discovery doc at https://ai.google.dev/api/rest.

add additional dart docs

---

pkgs/google_generative_ai/lib/google_generative_ai.dart
pkgs/google_generative_ai/pubspec.yaml

Improve package level docs

---

pkgs/google_generative_ai/lib/src/api.dart

- add additional dartdocs for enum values (from https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/configure-safety-attributes)
- move the enum parse methods so the enums know how to parse themselves

add additional dartdocs for enum values

---

pkgs/google_generative_ai/lib/src/model.dart

Taken from https://github.com/google/generative-ai-dart/pull/28

Improve docs on GenerativeModel

---

pkgs/google_generative_ai/CHANGELOG.md
pkgs/google_generative_ai/pubspec.yaml

Add a version and a CHANGELOG.
Remove `publish_to: none`.

Prepare to publish

---

samples/flutter_app/lib/main.dart

This adds a FocusNode to the text field that will request focus after a chat message is submitted.
cc: @loic-sharma
fixes #60

Request focus after submitting

---

pkgs/google_generative_ai/lib/src/chat.dart

The `_aggregate` function combines adjacent `TextPart`s in a sequence of lists of parts.
It was doing this by adding the text content of text parts to a `StringBuffer`, 
then creating a new text part from the result when no more text parts follows.
This change reuses the original text part when only a text part is not followed
by other text parts, instead of eagerly creating a new.
This version still writes the text of the first text part into the string buffer.
This is assumed to be cheap. If not, it can be delayed until the second text part
is seen, but that requires more logic per text node.

Make `_aggregate` not copy single `TextPart`s

---

.github/workflows/google_generative_ai.yml
pkgs/google_generative_ai/CHANGELOG.md
pkgs/google_generative_ai/lib/src/client.dart
pkgs/google_generative_ai/lib/src/version.dart
pkgs/google_generative_ai/pubspec.yaml
pkgs/google_generative_ai/tool/validate_version.dart

- validate that the package versions are kept in sync

validate that the package versions are kept in sync

---

.github/dependabot.yaml

- check for dependabot updates monthly

check for dependabot updates monthly

---

samples/dart/README.md
samples/flutter_app/README.md

- update aistudio.google.com urls

update aistudio.google.com urls

---

pkgs/google_generative_ai/lib/src/vertex_hooks.dart

Expose UsageMetadata and parse functions to vertex

Expose a few more class and functions to vertex

---

.github/workflows/google_generative_ai.yml
pkgs/google_generative_ai/CHANGELOG.md
pkgs/google_generative_ai/analysis_options.yaml
pkgs/google_generative_ai/lib/src/version.dart
pkgs/google_generative_ai/pubspec.yaml

- rev to the latest package:lints

rev to the latest package:lints

---

samples/dart/bin/configure_model_parameters.dart
samples/dart/bin/safety_settings.dart
samples/dart/bin/system_instructions.dart

Add samples that demonstrate setting generation config, safety settings,
and system instructions.

Add standard configuration samples
