- pkgs/google_generative_ai/lib/src/client.dart
- pkgs/google_generative_ai/lib/src/model.dart
This lets them:
1. pick the implementation
2. pool connections
> Allow the developer to use their own http.Client

- .github/workflows/google_generative_ai.yml
- pkgs/google_generative_ai/lib/src/client.dart
- pkgs/google_generative_ai/lib/src/content.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/generative_model_test.dart
- pkgs/google_generative_ai/test/http_api_client_test.dart
- pkgs/google_generative_ai/test/utils/matchers.dart
- pkgs/google_generative_ai/test/utils/stub_client.dart
Refactor `ApiClient` to go from `Map` to `Map` instead of bytes to
`String`. This makes it easier to write a stub client which is agnostic
to the ordering of values in the maps. Move the responsibilities for
UTF8 and JSON encoding to the `HttpApiClient`.
Eagerly call nested `.toJson()` methods for child fields in `.toJson()`
implementations. This allows deep equality checking for the stub client
without implementing `operator ==` for the data model classes.
Add a `createModelWithClient` method in `src/model.dart` which will not
be exported to the package public API. Use it in the test to create a
model with a stubbed client.
Add tests for each call in `GenerativeModel`. Tests validate
- Encoding from arguments to the JSON schema.
- Building the correct `Uri` for the task and model.
- …
> Add happy-path test cases for Model and ApiClient

- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
Strip a leading `models/` since the model names are often used with that
prefix. Store the field without the prefix so it can be used as a URI
path segment and no URI parts are constructed with string operations.
Change a call to `setUp` to define a method called from each test to
allow one case where the model name is overidden. Add a single test that
validates the  URI does not have a double `models/` segment.
> Normalize model names

- pkgs/google_generative_ai/lib/src/api.dart
This commit updates the `GenerationConfig` class to use `double?` instead of `int?` for the `temperature` and `topP` fields. 
This change aligns the Dart implementation with [Google's AI API Reference](https://ai.google.dev/api/rest/v1/GenerationConfig), which specifies these fields as numbers capable of holding fractional values. 
The adjustment ensures compatibility with the API's expected input types for controlling randomness (`temperature`) and the cumulative probability threshold (`topP`) in generated responses.
- Change `temperature` field type from `int?` to `double?`
- Change `topP` field type from `int?` to `double?`
Below are screenshots from Google AI Studio's code generation examples in Python and Koltin, highlighting the usage of `temperature` and `topP` as non-integer …
> Adjust temperature and topP types in GenerationConfig

- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/error.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
When parsing to a `GenerateContentResponse` fails with a format
exception, it may be due to the server responding with an "error"
response.
Add specific exception types for `InvalidApiKey` and
`UnsupportedUserLocation` since these errors may need specific handling
in a client. For now all other errors are a `ServerException`, but we
can add other types if it becomes useful to match more specific
patterns.
Add tests with scraped server error responses parsed to each error type.
Export the errors from the package public API.
Add a doc comment to the `GenerativeAIException` class from
https://github.com/google/generative-ai-dart/pull/28/files#diff-422b60b8e6460903ebe4ea03bef1a87c07ba50229d3f46bf436dc8ddd905d050
Fix a typo in the exception `toString()`.
> Add parsing for unary server errors

- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/lib/src/content.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/response_parsing_test.dart
- pkgs/google_generative_ai/test/utils/matchers.dart
Copy some known server responses from the Android SDK repo.
https://github.com/google/generative-ai-android/tree/main/generativeai/src/test/resources/golden-files/unary
Add tests for parsing a `GenerateContentResponse` from each server
response.
Support parsing a response with no candidates that has a prompt
feedback.
Add prompt feedback matching to the testing utilities.
Move the JSON object from the message string to the "source" argument
when throwing a `FormatException` as suggested in
https://github.com/google/generative-ai-dart/pull/28
Fix some typos.
> Add tests for parsing known server responses

- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
Closes #35
Add a `safetySettings` and `generationConfig` argument to
`generateContent` and `generateContentStream`.
> Allow overriding config per request

- pkgs/google_generative_ai/lib/src/chat.dart
- pkgs/google_generative_ai/test/chat_test.dart
Add a `safetySettings` and `genrationConfig` argument to the `startChat`
extension method. Store the configuration on the chat object and pass it
to `generateContent` when sending messages.
This is a followup to
https://github.com/google/generative-ai-dart/pull/38
> Allow specifying config when starting chat

- pkgs/google_generative_ai/lib/src/api.dart
The REST API discovery document lists `BLOCK_REASON_UNSPECIFIED` as the
enum value. There is no `UNKNOWN` listed.
> Fix wire format for unspecified block reason

- pkgs/google_generative_ai/lib/src/client.dart
Taken from https://github.com/google/generative-ai-dart/pull/28
- Fuse the utf8 and json codecs instead of applying them separately.
- Refactor to `async*` over manually using a `StreamController`.
> Refactor HttpApiClient

- samples/dart/bin/advanced_chat.dart
- samples/dart/bin/advanced_text.dart
- samples/dart/bin/advanced_text_and_image.dart
- samples/dart/bin/simple_chat.dart
- samples/dart/bin/simple_config.dart
- samples/dart/bin/simple_embedding.dart
- samples/dart/bin/simple_text.dart
- samples/dart/bin/simple_text_and_image.dart
- samples/dart/bin/util/resource.dart
Remove incorrect usage of `ParallelWaitError.errors` - it is not an
iterable. The error handling is not the interesting part of the sample
and it's more noise than is useful, so remove it. Inline the variable
declaration in both places where Record.wait is used. In both cases the
`late` was already unnecessary.
Apply fixes from https://github.com/google/generative-ai-dart/pull/28
- Write errors to `stederr`.
- Reference `message` var instead of repeat the string.
- Fix usage of Uri path to resolve resource files.
> Cleanup in sample code

- pkgs/google_generative_ai/lib/src/chat.dart
- pkgs/google_generative_ai/lib/src/utils/mutex.dart
- pkgs/google_generative_ai/pubspec.yaml
Taken from https://github.com/google/generative-ai-dart/pull/28
Replace `package:pool` with a small `Mutex` implementation. We don't
need the full capabilities of `Pool`, so remove the dependency.
Improve doc comments - rephrase, add missing docs, and improve
formatting.
Make `sendMessageStream` a synchronous method with an inner `async*`
function literal. This allows taking the lock synchronously instead of
waiting for the returned stream to have a listener. Add a TODO about
eagerly listening and buffering the response so that it can be added to
history as it arrives.
> Improve chat implementation

- .github/workflows/google_generative_ai.yml
For now only uses dart2js since tests are only ran on stable.
> Run tests on web

- pkgs/google_generative_ai/lib/src/chat.dart
- pkgs/google_generative_ai/test/chat_test.dart
The `sendRequestStream` function now sends the request eagerly, as soon as prior requests are done, whether someone is listening to the returned stream or not.
The stream will cache responses until listened to.
This should ensure that nobody listening on the stream won't affect the ordering of requests, or block later requests.
It was a remarkably easy change.
> Make `sendRequestStream` eager and caching.

- pkgs/google_generative_ai/lib/src/client.dart
- pkgs/google_generative_ai/test/http_api_client_test.dart
1. Removed the rogue `Client` creation i.e. `_httpClient = httpClient ?? http.Client();`
2. Fixed a bug where `makeRequest` did not use the developers `httpClient`
3. Added tests for the cases where the developer providers their own `httpClient`
> Fix a bug where the developer's `Client` was not used in unary requests

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/pubspec.yaml
These were copied from another SDK but were never used. The server will
not respond with any of the related values, and will not accept them as
input.
Rename to HarmCategory.unspecified since this was already the
encoded value.
> Drop unnecessary `unknown` enum values

- samples/flutter_app/lib/main.dart
- samples/flutter_app/macos/Runner/DebugProfile.entitlements
- samples/flutter_app/macos/Runner/Release.entitlements
The error message when there's no API key isn't super helpful: 
After:
> Makes the error text selectable and checks for API key

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/test/response_parsing_test.dart
Resolves #75 
There are two questions regarding this solution. I will change it if you think it should be different then I've implemented.
1. Do we want to return `CitationSource` with only nulls? It is technically a valid response from the API but doesn't make much sense.
2. What if uri parsing fails? Do we want to be more lenient and return `null`? Do we want to throw `FormatException`? Or do we expect that it will always be a valid URI if provided and leave it as is?
> Fix CitationSource parsing

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/pubspec.yaml
- rev to `0.2.1` in prep for publishing
This captures the two parsing fixes in #76 and #84.
> rev to 0.2.1

- .github/workflows/google_generative_ai.yml
- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/chat.dart
- pkgs/google_generative_ai/lib/src/client.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/utils/matchers.dart
- samples/dart/pubspec.yaml
Add workarounds for changes in inference which result in static errors.
Add ignores for since-fixed false positive diagnostics.
Test on a 3.0 SDK on CI.
> Add compatibility with older Dart SDK back to 3.0

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
Store the model code as a record with a prefix and name to allow
overriding the default `models/` path segment with `tunedModels/`.
> Add support for tuned models

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
- pkgs/google_generative_ai/test/utils/matchers.dart
Closes #96
This method was missed in the original implementation alongside
`embedContent`.
Add the overall model code when making requests without a model
specified - the back end requires the model field for batch requests.
- Add `BatchEmbedContentsResponse` and `EmbedContentRequest` classes and
serialization.
- Add the `batchEmbedContents` model method. As with the other methods
the top level `BatchEmbedContentsRequest` object fields are only
exposed as the method arguments.
- Add a happy path test case and a matcher utility for batch embed
responses.
> Add batchEmbedContents support

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/generative_model_test.dart
This API will be required for authors to use to try function calling
while the backend support is still in version `v1beta`.
Add a RequestOptions class. For now this supports only the `apiVersion`
configuration. In the future this may add a `timeout` (#44) if implement
a deeper HTTP timeout functionality than `Future.timeout`.
> Add support for overriding API version

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/chat.dart
- pkgs/google_generative_ai/lib/src/content.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/utils/matchers.dart
Adding only the support to refer to files which for now need to be
uploaded separately.
- Add a `FilePart` subclass of `Part` with a Uri argument for a file
uploaded to the google AI file service.
- Change an exhaustive switch on a `Part` to an if/else to avoid needing
to update for further new subtypes of `Part`.
> Add support for referring to uploaded files

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/function_calling.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/generative_model_test.dart
Function calling configuration allows specifying that the model must, or
must not, call a function on the current response. By default the model
is allowed to choose whether to call a function or reply in natural
language.
Add a `ToolConfig` class and a `toolConfig` argument to the
`GenerativeModel` constructor and the methods for generating content.
The classes and fields match the API model directly.
Add support for overriding the `tools` for a specific generate content
call from what was set during instantiation.
> Implement constrained function calling

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/chat_test.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
- samples/dart/bin/function_calling.dart
For consistency across the client and server focused SDKs, and because
the SDK entirely is in preview, switch to the beta API version by
default.
> Switch to API version v1beta

- README.md
- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/README.md
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
Add a note warning against leaking API keys with billing enabled in
client side applications.
Add to both the top-level README for this repository, as well as the
README published with the package and rendered on the pub site.
Drop `-wip` suffix from version to prepare for publish.
> Add caution note to READMEs

- pkgs/google_generative_ai/lib/src/model.dart
It's unlikely we will want to maintain copied information  about version
compatibility with the official docs, so link to them instead.
> Add link to API version doc

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- samples/dart/bin/advanced_text.dart
Add `UsageMetadata` and relevante parsing. Add a `usageMetadata` field
on `GenerateContentResponse`.
Add usage of the new field to the advanced text sample.
Refactor the `GenerateContentResponse` parse method to handled each
field individually at the top level. There is a behavior change for an
error case, but it is not visible through the message formats that are
returned from the backend in practice.
Prepare to publish.
> Add usageMetadata to GenerateContentResponse

- .gitattributes
Add a `.gitattributes` file with some patterns for files created by the
flutter templates.
This list is the patterns that look the least likely to be manually
edited, although there are many other files with generated (and
unedited) boilerplate that look like it _might_ change in a manual
commit at some point which will still add noise in new app PRs.
- `.metada`, `flutter/CMakeLists.txtx`,
`GenerateDPluginRegistrant.swift`, and the `generated_*` pattern files
have comments indicating they are generated and should not be edited.
- The `Runner.xcodeproj` and `Runner.xcworkspace` directories contain
xml files and look very unlikely to be hand-edited.
> Mark some flutter files as generated

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/function_calling.dart
Closes #130
Adds named constructors for each `SchemaType` enum value.
- Saves a few characters at the call site (no need to repeat the noisy
`SchemaType.` name).
- Restricts the arguments to those which are sensible for each type.
> Add named constructors for Schema types

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
This PR adds support for reducing the output dimensionality of the generated embeddings.
Related docs: 
- https://ai.google.dev/api/rest/v1beta/models/embedContent
- https://ai.google.dev/api/rest/v1beta/models/batchEmbedContents
> Add support for reduced output dimensionality in embeddings

- pkgs/google_generative_ai/test/chat_test.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
- pkgs/google_generative_ai/test/http_api_client_test.dart
- pkgs/google_generative_ai/test/response_parsing_test.dart
- pkgs/google_generative_ai/test/utils/matchers.dart
- pkgs/google_generative_ai/test/utils/stub_client.dart
An upcoming test refactor looks better when it's formatted with trailing
commas in more places. Pre-emptively format with inserted trailing
commas to make it easier to automate the formatting and reduce the diff
in the test refactor.
Trailing commas are inserted automatically by first formatting with the
`tall-style` experiment against the latest commit of `dart_style`, then
reformatting with the stable SDK to match CI expectations. The result
is the current formatting, with the trailing commas inferred where the
tall style has improved splitting. Blank lines are restored following
license header comments.
> Insert formatting trailing commas in tests

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/content.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/utils/matchers.dart
The vertex AI SDK will need new subtypes for parts which are not used on
the Google AI API. For instance in vertex referring to uploaded files
includes both the Uri and a mimetype, while on Google AI an uploaded
file stores it's own mime type and the Part only includes the Uri.
Prepare to publish to keep vertex unblocked.
> Unseal the Part class

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/content.dart
- samples/dart/bin/function_calling.dart
The alternative when replying to multiple functions in parallel is to
use the `Content` constructor and pass the string `'function'` to the
`role` parameter. Use a static method to obscure the role string for
consistency with the others.
Update sample with a demonstration of replying to all function calls.
> Add Content.functionResponses utility

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/response_parsing_test.dart
Prepare for cases where the model may reply with both text and a
function call.
When the text getter was introduced the cross-SDK approach was to return
the first text part. Now that multiple parts are more common with
function calling we decided to switch to concatenating the text.
I think this should be non-breaking in practice because current models
don't seem to respond with a text part when it isn't the single part.
> Join multiple text parts in the text getter

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/function_calling.dart
The `format` field was being ignored when using `Schema.number`or `Schema.integer` factories.
> Fix Schema.number and Schema.integer factories ignoring format field

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
This is a public field in `GenerateContentResponse` and was missed in
the export in #143. Resolves the missing API for vertex in #165.
> Export UsageMetadata from the main library

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/test/generative_model_test.dart
- samples/dart/bin/simple_text.dart
This will make the counted tokens aligned with what the model will count
if the same request were made to `generateContent`.
Extract the JSON conversion to a separate method and call it from
`generateContent`, `generateContentStream`, and `countTokens`.
> Include full GenerateContentRequest for countTokens

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/test/response_parsing_test.dart
Closes #99
Call out that candidates may be ignored in the doc for
`GenerateContentResponse.text`.
Add a `text` getter on `Candidate`. This is the same logic that was in
the response text getter, applied to an individual candidate.
Refactor the response text implementation to use the candidate field.
> Add a text getter for Candidate

- README.md
- pkgs/google_generative_ai/README.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/model.dart
- samples/dart/bin/advanced_chat.dart
- samples/dart/bin/advanced_text.dart
- samples/dart/bin/advanced_text_and_image.dart
- samples/dart/bin/guessing_game.dart
- samples/dart/bin/simple_chat.dart
- samples/dart/bin/simple_config.dart
- samples/dart/bin/simple_text.dart
- samples/dart/bin/simple_text_and_image.dart
- samples/flutter_app/lib/main.dart
Gemini documentation is standardizing on using versioned model names.
Use `gemini-1.5-flash-latest` for most use cases. Since this model is
multimodal it can replace both `1.0-pro` and `1.0-pro-vision` usage.
Combine the models in the flutter app to one.
Use `gemini-1.5.-pro-latest` for the example with force function calling
(`FunctionCallingMode.any`) since that is unsupported in the flash
model.
Also use the pro model for the other function calling sample. The flash
model should support this in theory, but when I run it in practice it
fails to call the functions.
> Use updated gemini model names

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/model.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/lib/src/vertex_hooks.dart
- pkgs/google_generative_ai/pubspec.yaml
Maintains the internal details of using the client, but offers a general
escape hatch for any unary request by exposing `Task`.
Add a `makeRequest` utility method in an extension, and update the
existing unary requests to use it.
> Add a request escape hatch for the vertex SDK

- samples/dart/bin/function_calling.dart
Align the prompt and function definition used in the function calling
sample with the cross-language canonical sample.
Move the dispatch helper function from the top level to a local function
to keep the full details within the sample region.
> Rewrite function calling sample to standard prompt

- samples/dart/bin/controlled_generation.dart
Add a `controlled_generation.dart` library with samples of requesting
JSON results back, using both a Schema object and a textual schema
directly in the prompt.
> Add JSON output standard sample

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/api.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/response_parsing_test.dart
Fixes #184
The vertex backend uses a similar data model, but names the field
`citations` instead of `citationSources`. Read either field, whichever
exists, and parse it otherwise consistently.
> Allow Vertex formatted CitationMetadata

- samples/dart/README.md
- samples/dart/bin/advanced_chat.dart
- samples/dart/bin/advanced_text.dart
- samples/dart/bin/advanced_text_and_image.dart
- samples/dart/bin/guessing_game.dart
- samples/dart/bin/safety_settings.dart
- samples/dart/bin/simple_chat.dart
- samples/dart/bin/simple_config.dart
- samples/dart/bin/simple_embedding.dart
- samples/dart/bin/simple_text.dart
- samples/dart/bin/simple_text_and_image.dart
- samples/dart/bin/system_instructions.dart
- samples/flutter_app/README.md
The standardized samples are already using `GEMINI_API_KEY`.
https://github.com/google-gemini/generative-ai-dart/pull/188#discussion_r1676329979
Update the non-standard samples to use the same.
> Rename GOOGLE_API_KEY as GEMINI_API_KEY

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/google_generative_ai.dart
- pkgs/google_generative_ai/lib/src/content.dart
- pkgs/google_generative_ai/lib/src/function_calling.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
- pkgs/google_generative_ai/test/generative_model_test.dart
- pkgs/google_generative_ai/test/response_parsing_test.dart
- pkgs/google_generative_ai/test/utils/matchers.dart
- samples/dart/bin/code_execution.dart
Add `CodeExecutionResult` and `ExecutableCode` which are new `Part`
subtypes that the model may reply with when code execution is enabled.
Add `CodeExecution` configuration class as a marker to enable code
execution. In the future additional configuration parameters may be
added
Add the standardized samples for code execution through the model and a
chat.
Add tests for forwarding configuration and parsing.
Bump version and prepare to publish.
> Add support for code execution

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/chat.dart
Fixes #197
A content requires a role when it is sent to the model in the history.
If the backend happens to respond with a message that has no role,
default it to 'model'.
> Default the role to 'model' for chat responses

- pkgs/google_generative_ai/CHANGELOG.md
- pkgs/google_generative_ai/lib/src/client.dart
- pkgs/google_generative_ai/lib/src/version.dart
- pkgs/google_generative_ai/pubspec.yaml
This is a simple throw give a clear message about the error when the server is not able to generate the content.
Aims to solve the Issue #206.
> Server error handling when generating content
